name: CI/CD Pipeline

# master 브랜치에 push나 pull request가 있을 때 실행된다.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # EC2 키 설정
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key-pair-secret.pem
          chmod 600 key-pair-secret.pem

      # ubuntu 접속 및 코드 최신화 재실행
      - name: SSH to EC2 and update code
        run: |
          ssh -i key-pair-secret.pem -o StrictHostKeyChecking=no -o ConnectTimeout=30 ubuntu@${{ secrets.EC2_IP }} << 'EOF'
          set -e
          echo "===== Connecting to server and updating code ====="
          cd /home/ubuntu/assignment || exit 1

          # 현재 서버 상태 확인
          echo "Current PM2 status:"
          pm2 status || true

          # 기존 프로세스 종료
          echo "Stopping previous server instance..."
          pm2 kill || true

          # 코드 업데이트
          echo "Pulling latest code..."
                  git config pull.rebase false
          git pull origin master

          # 종속성 설치 및 빌드
          echo "Installing dependencies..."
                  npm install
          echo "Building project..."
          npm run build

          # 서버 재시작
          echo "Starting server..."
          pm2 start dist/main.js --name "nest-server"

          sleep 5
          pm2 status

          echo "===== Deployment completed successfully ====="
          EOF
